export interface IAppraisal {
  accountNumber?: number;
  accountNumber2?: number;
  apiRequestId?: number;
  applicantName: string;
  applicationAmount: number;
  applicationDate: string;
  applicationDateArch?: string;
  applicationDetails?: any;
  applicationReferenceNumber: string;
  applicationStatus?: any;
  applicationStatusId?: number;
  applicationTenor?: number;
  applicationUrl?: string;
  approvalLevelId?: number;
  approvalStatus?: any;
  approvalStatusId: number;
  approvalStatusName?: any;
  approvalTrailId: number;
  approvedAmount?: number;
  approvedProductId?: number;
  approvedProductName?: any;
  approvedTenor?: number;
  bookingDate?: any;
  bookingOperationId?: any;
  bookingRequestId?: number;
  branchId: number;
  branchName: string;
  canModified: boolean;
  cancellationReason?: any;
  casaAccountId?: any;
  closeApplication: boolean;
  collateralDetail: string;
  comment?: any;
  company?: any;
  companyId?: number;
  companyName?: any;
  countryId: number;
  createdBy: number;
  creatorName?: any;
  creditAppraisalLoanApplicationId?: number;
  creditAppraisalOperationId?: number;
  currency?: any;
  currencyCode?: any;
  currencyId: number;
  currencyName?: any;
  currentApprovalLevel: string;
  currentApprovalLevelId: number;
  currentApprovalLevelSlaInterval: number;
  currentApprovalLevelTypeId?: any;
  currentApprovalStateId: number;
  currentOperationId?: number;
  customerAccount?: any;
  customerBusinessUnitId: number;
  customerCode?: any;
  customerGroupCode?: any;
  customerGroupId?: any;
  customerGroupName: string;
  customerId: number;
  customerInfoValidated: boolean;
  customerName: string;
  customerType?: any;
  customerTypeId: 1;
  datePastDue?: any;
  dateTimeAndTimeOfDay?: any;
  dateTimeCreated: string;
  dateTimeDeleted?: any;
  dateTimeUpdated?: any;
  daysPastDue?: number;
  deleted: boolean;
  deletedBy?: any;
  details?: any;
  divisionCode: string;
  divisionShortCode: string;
  editMode: boolean;
  effectiveDate?: any;
  employer?: any;
  equityControl?: any;
  exchangeRate?: number;
  exclusiveOperationId?: any;
  expiryDate?: any;
  facility: string;
  facilityAmount?: number;
  failedRacStartCam: boolean;
  firstName?: any;
  flowchangeId?: any;
  globalsla: 1;
  groupRoleId?: number;
  interestRate?: number;
  isAtDrawDown: boolean;
  isCollateralBacked: boolean;
  isEmployerRelated: boolean;
  isFacilityCreated?: any;
  isInterventionFunds: boolean;
  isInvestmentGrade: boolean;
  isNewApplication: boolean;
  isORRBasedApproval: boolean;
  isOfferLetterAvailable: boolean;
  isOnLending: boolean;
  isPoliticallyExposed: boolean;
  isProjectRelated?: any;
  isProjectRelatedLoan: boolean;
  isRelatedParty: boolean;
  isSkipAppraisalEnabled: boolean;
  isTakeOverApplication?: any;
  isadhocapplication: boolean;
  jumpedDestination: boolean;
  lastComment: string;
  lastName?: any;
  lastUpdatedBy?: number;
  legalContingentCode?: any;
  lienAmount?: number;
  lienDateTimeCreated: string;
  lienReferenceNumber?: any;
  lmsApplicationDetailId?: number;
  loanApplicationCollateral?: any;
  loanApplicationDetail: Array<any>;
  loanApplicationDetailId?: number;
  loanApplicationId: number;
  loanApplicationIdForOperation?: any;
  loanApprovedLimitId?: any;
  loanId?: any;
  loanInformation: string;
  loanPreliminaryEvaluationId?: any;
  loanPurpose?: any;
  loanReferenceNumber?: any;
  loanStatus?: any;
  loanStatusId?: number;
  loanSystemTypeId?: number;
  loanTypeId: number;
  loanTypeName: string;
  loansWithOthers?: number;
  loantermSheetCode?: any;
  loantermSheetId?: any;
  maturityDate?: any;
  middleName?: any;
  misCode: string;
  monthlyPayment?: number;
  moratrium?: any;
  newApplicationDate?: any;
  notInBlackbook: boolean;
  notInCamsol: boolean;
  notInCrc: boolean;
  notInNegativeCrms: boolean;
  notInXds: boolean;
  operationId: number;
  operationName?: any;
  operationTypeName?: any;
  owner: boolean;
  ownershipStructure?: any;
  passCode?: any;
  pledgeCollateral?: any;
  principalAmount?: number;
  productClassId: number;
  productClassName: string;
  productClassProcessId: 1;
  productId?: number;
  productName?: any;
  productTypeId?: number;
  proposedAmount?: number;
  proposedInterestRate?: number;
  proposedProductId?: number;
  proposedProductName?: any;
  proposedTenor?: number;
  psrReportTypeId?: number;
  rac?: any;
  referenceNumber?: any;
  regionId: number;
  relatedEmployerId?: any;
  relatedReferenceNumber?: any;
  relationshipManagerId: number;
  relationshipManagerName: string;
  relationshipOfficerId: number;
  relationshipOfficerName: string;
  repaymentScheduleId?: any;
  repaymentTerm?: any;
  reportTypeName?: any;
  requireCollateral: true;
  requireCollateralTypeId: number;
  responseStaffId?: any;
  responsiblePerson?: any;
  reviewLoanDetaile?: any;
  sectorId?: number;
  sectorName?: any;
  singleCustomerId?: any;
  slaGlobalStatus: string;
  slaInduvidualStatus: string;
  slaTime: string;
  sourceBranchId?: number;
  sourceReferenceNumber?: any;
  staffId?: number;
  staffName?: any;
  subSectorId?: number;
  submittedForAppraisal: boolean;
  systemArrivalDateTime?: any;
  systemCurrentDate?: any;
  systemDateTime: string;
  teamMisCode?: any;
  
  tempApplicationCancellationId?: number;
  tenor?: number;
  tenorModeId?: number;
  tenorModeName?: any;
  tenorString: string;
  termSheetCode?: any;
  timeIn: string;
  timeLapse: string;
  toStaffId: number;
  totalUtilized?: number;
  tranchLevelId?: any;
  userBranchId?: number;
  userIPAddress?: any;
  username?: any;
  valueOfCollateral?: number;
  success: boolean;
}

export const TestAppraisal: IAppraisal[] = [
  {
    productTypeId: 0,
    totalUtilized: 0.0,
    customerBusinessUnitId: 1,
    divisionShortCode: "CIBD",
    bookingRequestId: 0,
    divisionCode: "IBG800",
    approvedProductName: null,
    equityControl: null,
    moratrium: null,
    pledgeCollateral: null,
    valueOfCollateral: 0.0,
    reportTypeName: null,
    psrReportTypeId: 0,
    facility: "TERM LOANS - PAST DU",
    isFacilityCreated: null,
    owner: false,
    currentOperationId: 0,
    jumpedDestination: false,
    failedRacStartCam: false,
    isNewApplication: false,
    closeApplication: false,
    loanApplicationId: 19755,
    loanApplicationIdForOperation: null,
    loanApplicationDetailId: 0,
    applicationReferenceNumber: "1312468800341",
    customerId: 20763,
    operationId: 153,
    requireCollateral: true,
    newApplicationDate: null,
    loansWithOthers: 0.0,
    ownershipStructure: null,
    branchId: 94,
    productClassId: 1,
    productClassName: "Non-Credit Program",
    productId: 0,
    customerGroupId: null,
    customerGroupCode: null,
    loanTypeId: 1,
    casaAccountId: null,
    currencyId: 1,
    currencyCode: null,
    loanStatusId: 0,
    loanStatus: null,
    relationshipOfficerId: 8379,
    relationshipManagerId: 8379,
    daysPastDue: 0,
    datePastDue: null,
    applicationDate: "2020-08-06T00:00:00+00:00",
    applicationDateArch: null,
    applicationAmount: 16000000.0,
    approvedAmount: 0.0,
    monthlyPayment: 0.0,
    applicationTenor: 210.0,
    interestRate: 0.0,
    effectiveDate: null,
    bookingDate: null,
    maturityDate: null,
    expiryDate: null,
    customerAccount: null,
    tenorModeId: 0,
    loanInformation: "<p></p>",
    misCode: "001",
    teamMisCode: null,
    submittedForAppraisal: false,
    operationName: null,
    isRelatedParty: false,
    isPoliticallyExposed: false,
    isInvestmentGrade: false,
    isProjectRelatedLoan: false,
    isOnLending: false,
    isInterventionFunds: false,
    isORRBasedApproval: false,
    approvalStatusId: 1,
    proposedAmount: 0.0,
    proposedTenor: 0,
    approvalLevelId: 0,
    subSectorId: 0,
    sectorId: 0,
    sectorName: null,
    loantermSheetCode: null,
    customerName: "Buchi Test Inc  ",
    customerTypeId: 1,
    branchName: "Victoria Island",
    productName: null,
    customerGroupName: "",
    termSheetCode: null,
    loanTypeName: "Single Customer",
    relationshipOfficerName: "IBHANDE  OKOGUN",
    relationshipManagerName: "IBHANDE  OKOGUN",
    tenorModeName: null,
    applicantName: "Buchi Test Inc  ()",
    lmsApplicationDetailId: 0,
    loanPreliminaryEvaluationId: null,
    loantermSheetId: null,
    exchangeRate: 0.0,
    loanApplicationCollateral: null,
    loanApplicationDetail: [],
    details: null,
    currentApprovalStateId: 2,
    currentApprovalLevelId: 228,
    currentApprovalLevel: "ACCOUNT OFFICER",
    lastComment: "New loan application",
    approvalTrailId: 142148,
    responseStaffId: null,
    applicationStatusId: 14,
    isCollateralBacked: false,
    collateralDetail: "",
    loanPurpose: null,
    tenor: 0,
    apiRequestId: null,
    customerInfoValidated: false,
    notInNegativeCrms: false,
    notInBlackbook: false,
    notInCamsol: false,
    notInXds: false,
    notInCrc: false,
    firstName: null,
    middleName: null,
    customerCode: null,
    proposedProductId: 0,
    repaymentTerm: null,
    isTakeOverApplication: null,
    repaymentScheduleId: null,
    proposedInterestRate: 0.0,
    proposedProductName: null,
    approvedProductId: 0,
    currencyName: null,
    lastName: null,
    groupRoleId: 0,
    accountNumber: null,
    accountNumber2: null,
    applicationStatus: null,
    relatedReferenceNumber: null,
    toStaffId: 8379,
    productClassProcessId: 1,
    approvalStatus: null,
    responsiblePerson: null,
    timeIn: "2021-08-20T22:09:22.05+00:00",
    slaTime: "2021-08-20T22:09:22.05+00:00",
    cancellationReason: null,
    globalsla: 1,
    currentApprovalLevelSlaInterval: 24,
    isadhocapplication: false,
    isSkipAppraisalEnabled: false,
    isAtDrawDown: false,
    exclusiveOperationId: null,
    flowchangeId: null,
    loanApprovedLimitId: null,
    approvedTenor: 0,
    applicationDetails: null,
    approvalStatusName: null,
    tenorString: "7 months",
    timeLapse: "61 days",
    tempApplicationCancellationId: 0,
    staffName: null,
    creatorName: null,
    comment: null,
    isOfferLetterAvailable: false,
    currentApprovalLevelTypeId: null,
    tranchLevelId: null,
    regionId: 1,
    editMode: false,
    requireCollateralTypeId: 3,
    rac: null,
    dateTimeAndTimeOfDay: null,
    slaGlobalStatus: "danger",
    slaInduvidualStatus: "danger",
    customerType: null,
    isProjectRelated: null,
    facilityAmount: 0.0,
    operationTypeName: null,
    reviewLoanDetaile: null,
    referenceNumber: null,
    systemDateTime: "2021-08-20T22:06:11.047+00:00",
    bookingOperationId: null,
    sourceReferenceNumber: null,
    lienReferenceNumber: null,
    lienAmount: 0.0,
    lienDateTimeCreated: "0001-01-01T00:00:00+00:00",
    currency: null,
    principalAmount: 0.0,
    loanReferenceNumber: null,
    loanId: null,
    loanSystemTypeId: 0,
    legalContingentCode: null,
    singleCustomerId: null,
    isEmployerRelated: false,
    relatedEmployerId: null,
    employer: null,
    creditAppraisalOperationId: 0,
    creditAppraisalLoanApplicationId: 0,
    companyId: 0,
    companyName: null,
    company: null,
    createdBy: 8379,
    lastUpdatedBy: 0,
    dateTimeCreated: "2020-08-06T00:00:00+00:00",
    dateTimeUpdated: null,
    deleted: false,
    deletedBy: null,
    dateTimeDeleted: null,
    canModified: false,
    userBranchId: 0,
    sourceBranchId: 0,
    userIPAddress: null,
    applicationUrl: null,
    systemCurrentDate: null,
    systemArrivalDateTime: null,
    staffId: 0,
    username: null,
    passCode: null,
    countryId: 2,
    success: false,
  },
  {
    productTypeId: 0,
    totalUtilized: 0.0,
    customerBusinessUnitId: 1,
    divisionShortCode: "CIBD",
    bookingRequestId: 0,
    divisionCode: "IBG800",
    approvedProductName: null,
    equityControl: null,
    moratrium: null,
    pledgeCollateral: null,
    valueOfCollateral: 0.0,
    reportTypeName: null,
    psrReportTypeId: 0,
    facility: "Multilple(2)",
    isFacilityCreated: null,
    owner: false,
    currentOperationId: 0,
    jumpedDestination: false,
    failedRacStartCam: false,
    isNewApplication: false,
    closeApplication: false,
    loanApplicationId: 19756,
    loanApplicationIdForOperation: null,
    loanApplicationDetailId: 0,
    applicationReferenceNumber: "1312547758897",
    customerId: 20763,
    operationId: 153,
    requireCollateral: true,
    newApplicationDate: null,
    loansWithOthers: 0.0,
    ownershipStructure: null,
    branchId: 94,
    productClassId: 1,
    productClassName: "Non-Credit Program",
    productId: 0,
    customerGroupId: null,
    customerGroupCode: null,
    loanTypeId: 1,
    casaAccountId: null,
    currencyId: 1,
    currencyCode: null,
    loanStatusId: 0,
    loanStatus: null,
    relationshipOfficerId: 8379,
    relationshipManagerId: 8379,
    daysPastDue: 0,
    datePastDue: null,
    applicationDate: "2020-08-06T00:00:00+00:00",
    applicationDateArch: null,
    applicationAmount: 38000000.0,
    approvedAmount: 0.0,
    monthlyPayment: 0.0,
    applicationTenor: 210.0,
    interestRate: 0.0,
    effectiveDate: null,
    bookingDate: null,
    maturityDate: null,
    expiryDate: null,
    customerAccount: null,
    tenorModeId: 0,
    loanInformation: "<p></p>",
    misCode: "001",
    teamMisCode: null,
    submittedForAppraisal: false,
    operationName: null,
    isRelatedParty: false,
    isPoliticallyExposed: false,
    isInvestmentGrade: false,
    isProjectRelatedLoan: false,
    isOnLending: false,
    isInterventionFunds: false,
    isORRBasedApproval: false,
    approvalStatusId: 1,
    proposedAmount: 0.0,
    proposedTenor: 0,
    approvalLevelId: 0,
    subSectorId: 0,
    sectorId: 0,
    sectorName: null,
    loantermSheetCode: null,
    customerName: "Buchi Test Inc  ",
    customerTypeId: 1,
    branchName: "Victoria Island",
    productName: null,
    customerGroupName: "",
    termSheetCode: null,
    loanTypeName: "Single Customer",
    relationshipOfficerName: "IBHANDE  OKOGUN",
    relationshipManagerName: "IBHANDE  OKOGUN",
    tenorModeName: null,
    applicantName: "Buchi Test Inc  ()",
    lmsApplicationDetailId: 0,
    loanPreliminaryEvaluationId: null,
    loantermSheetId: null,
    exchangeRate: 0.0,
    loanApplicationCollateral: null,
    loanApplicationDetail: [],
    details: null,
    currentApprovalStateId: 2,
    currentApprovalLevelId: 228,
    currentApprovalLevel: "ACCOUNT OFFICER",
    lastComment: "New loan application",
    approvalTrailId: 142048,
    responseStaffId: null,
    applicationStatusId: 14,
    isCollateralBacked: false,
    collateralDetail: "",
    loanPurpose: null,
    tenor: 0,
    apiRequestId: null,
    customerInfoValidated: false,
    notInNegativeCrms: false,
    notInBlackbook: false,
    notInCamsol: false,
    notInXds: false,
    notInCrc: false,
    firstName: null,
    middleName: null,
    customerCode: null,
    proposedProductId: 0,
    repaymentTerm: null,
    isTakeOverApplication: null,
    repaymentScheduleId: null,
    proposedInterestRate: 0.0,
    proposedProductName: null,
    approvedProductId: 0,
    currencyName: null,
    lastName: null,
    groupRoleId: 0,
    accountNumber: null,
    accountNumber2: null,
    applicationStatus: null,
    relatedReferenceNumber: null,
    toStaffId: 8379,
    productClassProcessId: 1,
    approvalStatus: null,
    responsiblePerson: null,
    timeIn: "2021-08-04T15:41:00.96+00:00",
    slaTime: "2021-08-04T15:41:00.96+00:00",
    cancellationReason: null,
    globalsla: 1,
    currentApprovalLevelSlaInterval: 24,
    isadhocapplication: false,
    isSkipAppraisalEnabled: false,
    isAtDrawDown: false,
    exclusiveOperationId: null,
    flowchangeId: null,
    loanApprovedLimitId: null,
    approvedTenor: 0,
    applicationDetails: null,
    approvalStatusName: null,
    tenorString: "7 months",
    timeLapse: "77 days",
    tempApplicationCancellationId: 0,
    staffName: null,
    creatorName: null,
    comment: null,
    isOfferLetterAvailable: false,
    currentApprovalLevelTypeId: null,
    tranchLevelId: null,
    regionId: 1,
    editMode: false,
    requireCollateralTypeId: 1,
    rac: null,
    dateTimeAndTimeOfDay: null,
    slaGlobalStatus: "danger",
    slaInduvidualStatus: "danger",
    customerType: null,
    isProjectRelated: null,
    facilityAmount: 0.0,
    operationTypeName: null,
    reviewLoanDetaile: null,
    referenceNumber: null,
    systemDateTime: "2021-08-04T15:39:58.663+00:00",
    bookingOperationId: null,
    sourceReferenceNumber: null,
    lienReferenceNumber: null,
    lienAmount: 0.0,
    lienDateTimeCreated: "0001-01-01T00:00:00+00:00",
    currency: null,
    principalAmount: 0.0,
    loanReferenceNumber: null,
    loanId: null,
    loanSystemTypeId: 0,
    legalContingentCode: null,
    singleCustomerId: null,
    isEmployerRelated: false,
    relatedEmployerId: null,
    employer: null,
    creditAppraisalOperationId: 0,
    creditAppraisalLoanApplicationId: 0,
    companyId: 0,
    companyName: null,
    company: null,
    createdBy: 8379,
    lastUpdatedBy: 0,
    dateTimeCreated: "2020-08-06T00:00:00+00:00",
    dateTimeUpdated: null,
    deleted: false,
    deletedBy: null,
    dateTimeDeleted: null,
    canModified: false,
    userBranchId: 0,
    sourceBranchId: 0,
    userIPAddress: null,
    applicationUrl: null,
    systemCurrentDate: null,
    systemArrivalDateTime: null,
    staffId: 0,
    username: null,
    passCode: null,
    countryId: 2,
    success: false,
  },
  {
    productTypeId: 0,
    totalUtilized: 0.0,
    customerBusinessUnitId: 1,
    divisionShortCode: "CIBD",
    bookingRequestId: 0,
    divisionCode: "IBG800",
    approvedProductName: null,
    equityControl: null,
    moratrium: null,
    pledgeCollateral: null,
    valueOfCollateral: 0.0,
    reportTypeName: null,
    psrReportTypeId: 0,
    facility: "TERM LOANS - PAST DU",
    isFacilityCreated: null,
    owner: false,
    currentOperationId: 0,
    jumpedDestination: false,
    failedRacStartCam: false,
    isNewApplication: false,
    closeApplication: false,
    loanApplicationId: 19731,
    loanApplicationIdForOperation: null,
    loanApplicationDetailId: 0,
    applicationReferenceNumber: "1311168748899",
    customerId: 20763,
    operationId: 133,
    requireCollateral: true,
    newApplicationDate: null,
    loansWithOthers: 0.0,
    ownershipStructure: null,
    branchId: 94,
    productClassId: 1,
    productClassName: "Non-Credit Program",
    productId: 0,
    customerGroupId: null,
    customerGroupCode: null,
    loanTypeId: 1,
    casaAccountId: null,
    currencyId: 1,
    currencyCode: null,
    loanStatusId: 0,
    loanStatus: null,
    relationshipOfficerId: 8379,
    relationshipManagerId: 8379,
    daysPastDue: 0,
    datePastDue: null,
    applicationDate: "2020-08-04T00:00:00+00:00",
    applicationDateArch: null,
    applicationAmount: 19000000.0,
    approvedAmount: 0.0,
    monthlyPayment: 0.0,
    applicationTenor: 120.0,
    interestRate: 0.0,
    effectiveDate: null,
    bookingDate: null,
    maturityDate: null,
    expiryDate: null,
    customerAccount: null,
    tenorModeId: 0,
    loanInformation: "<p></p>",
    misCode: "001",
    teamMisCode: null,
    submittedForAppraisal: false,
    operationName: null,
    isRelatedParty: false,
    isPoliticallyExposed: false,
    isInvestmentGrade: false,
    isProjectRelatedLoan: false,
    isOnLending: false,
    isInterventionFunds: false,
    isORRBasedApproval: false,
    approvalStatusId: 1,
    proposedAmount: 0.0,
    proposedTenor: 0,
    approvalLevelId: 0,
    subSectorId: 0,
    sectorId: 0,
    sectorName: null,
    loantermSheetCode: null,
    customerName: "Buchi Test Inc  ",
    customerTypeId: 1,
    branchName: "Victoria Island",
    productName: null,
    customerGroupName: "",
    termSheetCode: null,
    loanTypeName: "Single Customer",
    relationshipOfficerName: "",
    relationshipManagerName: "",
    tenorModeName: null,
    applicantName: "",
    lmsApplicationDetailId: 0,
    loanPreliminaryEvaluationId: null,
    loantermSheetId: null,
    exchangeRate: 0.0,
    loanApplicationCollateral: null,
    loanApplicationDetail: [],
    details: null,
    currentApprovalStateId: 2,
    currentApprovalLevelId: 228,
    currentApprovalLevel: "ACCOUNT OFFICER",
    lastComment: "New loan application",
    approvalTrailId: 141595,
    responseStaffId: null,
    applicationStatusId: 14,
    isCollateralBacked: false,
    collateralDetail: "",
    loanPurpose: null,
    tenor: 0,
    apiRequestId: null,
    customerInfoValidated: false,
    notInNegativeCrms: false,
    notInBlackbook: false,
    notInCamsol: false,
    notInXds: false,
    notInCrc: false,
    firstName: null,
    middleName: null,
    customerCode: null,
    proposedProductId: 0,
    repaymentTerm: null,
    isTakeOverApplication: null,
    repaymentScheduleId: null,
    proposedInterestRate: 0.0,
    proposedProductName: null,
    approvedProductId: 0,
    currencyName: null,
    lastName: null,
    groupRoleId: 0,
    accountNumber: null,
    accountNumber2: null,
    applicationStatus: null,
    relatedReferenceNumber: null,
    toStaffId: 8379,
    productClassProcessId: 1,
    approvalStatus: null,
    responsiblePerson: null,
    timeIn: "2021-07-19T13:39:41.143+00:00",
    slaTime: "2021-07-19T13:39:41.143+00:00",
    cancellationReason: null,
    globalsla: 1,
    currentApprovalLevelSlaInterval: 24,
    isadhocapplication: true,
    isSkipAppraisalEnabled: false,
    isAtDrawDown: false,
    exclusiveOperationId: null,
    flowchangeId: null,
    loanApprovedLimitId: null,
    approvedTenor: 0,
    applicationDetails: null,
    approvalStatusName: null,
    tenorString: "4 months",
    timeLapse: "93 days",
    tempApplicationCancellationId: 0,
    staffName: null,
    creatorName: null,
    comment: null,
    isOfferLetterAvailable: false,
    currentApprovalLevelTypeId: null,
    tranchLevelId: null,
    regionId: 1,
    editMode: false,
    requireCollateralTypeId: 3,
    rac: null,
    dateTimeAndTimeOfDay: null,
    slaGlobalStatus: "danger",
    slaInduvidualStatus: "danger",
    customerType: null,
    isProjectRelated: null,
    facilityAmount: 0.0,
    operationTypeName: null,
    reviewLoanDetaile: null,
    referenceNumber: null,
    systemDateTime: "",
    bookingOperationId: null,
    sourceReferenceNumber: null,
    lienReferenceNumber: null,
    lienAmount: 0.0,
    lienDateTimeCreated: "",
    currency: null,
    principalAmount: 0.0,
    loanReferenceNumber: null,
    loanId: null,
    loanSystemTypeId: 0,
    legalContingentCode: null,
    singleCustomerId: null,
    isEmployerRelated: false,
    relatedEmployerId: null,
    employer: null,
    creditAppraisalOperationId: 0,
    creditAppraisalLoanApplicationId: 0,
    companyId: 0,
    companyName: null,
    company: null,
    createdBy: 8379,
    lastUpdatedBy: 0,
    dateTimeCreated: "",
    dateTimeUpdated: null,
    deleted: false,
    deletedBy: null,
    dateTimeDeleted: null,
    canModified: false,
    userBranchId: 0,
    sourceBranchId: 0,
    userIPAddress: null,
    applicationUrl: null,
    systemCurrentDate: null,
    systemArrivalDateTime: null,
    staffId: 0,
    username: null,
    passCode: null,
    countryId: 2,
    success: false,
  },
];


export interface IAppraisalSub {
  accountNumber?: number;
  accountNumber2?: number;
  apiRequestId?: number;
  applicantName: string;
  applicationAmount: number;
  applicationDate: string;
  applicationDateArch?: string;
  applicationDetails?: any;
  applicationReferenceNumber: string;
  applicationStatus?: any;
  applicationStatusId?: number;
  applicationTenor?: number;
  applicationUrl?: string;
  approvalLevelId?: number;
  approvalStatus?: any;
  approvalStatusId: number;
  approvalStatusName?: any;
  approvalTrailId: number;
  approvedAmount?: number;
  approvedProductId?: number;
  approvedProductName?: any;
  approvedTenor?: number;
  bookingDate?: any;
  bookingOperationId?: any;
  bookingRequestId?: number;
  branchId: number;
  branchName: string;
  canModified: boolean;
  cancellationReason?: any;
  casaAccountId?: any;
  closeApplication: boolean;
  collateralDetail: string;
  comment?: any;
  company?: any;
  companyId?: number;
  companyName?: any;
  countryId: number;
  createdBy: number;
  creatorName?: any;
  creditAppraisalLoanApplicationId?: number;
  creditAppraisalOperationId?: number;
  currency?: any;
  currencyCode?: any;
  currencyId: number;
  currencyName?: any;
  currentApprovalLevel: string;
  currentApprovalLevelId: number;
  currentApprovalLevelSlaInterval: number;
  currentApprovalLevelTypeId?: any;
  currentApprovalStateId: number;
  currentOperationId?: number;
  customerAccount?: any;
  customerBusinessUnitId: number;
  customerCode?: any;
  customerGroupCode?: any;
  customerGroupId?: any;
  customerGroupName: string;
  customerId: number;
  customerInfoValidated: boolean;
  customerName: string;
  customerType?: any;
  customerTypeId: 1;
  datePastDue?: any;
  dateTimeAndTimeOfDay?: any;
  dateTimeCreated: string;
  dateTimeDeleted?: any;
  dateTimeUpdated?: any;
  daysPastDue?: number;
  deleted: boolean;
  deletedBy?: any;
  details?: any;
  divisionCode: string;
  divisionShortCode: string;
  editMode: boolean;
  effectiveDate?: any;
  employer?: any;
  equityControl?: any;
  exchangeRate?: number;
  exclusiveOperationId?: any;
  expiryDate?: any;
  facility: string;
  facilityAmount?: number;
  failedRacStartCam: boolean;
  firstName?: any;
  flowchangeId?: any;
  globalsla: 1;
  groupRoleId?: number;
  interestRate?: number;
  isAtDrawDown: boolean;
  isCollateralBacked: boolean;
  isEmployerRelated: boolean;
  isFacilityCreated?: any;
  isInterventionFunds: boolean;
  isInvestmentGrade: boolean;
  isNewApplication: boolean;
  isORRBasedApproval: boolean;
  isOfferLetterAvailable: boolean;
  isOnLending: boolean;
  isPoliticallyExposed: boolean;
  isProjectRelated?: any;
  isProjectRelatedLoan: boolean;
  isRelatedParty: boolean;
  isSkipAppraisalEnabled: boolean;
  isTakeOverApplication?: any;
  isadhocapplication: boolean;
  jumpedDestination: boolean;
  lastComment: string;
  lastName?: any;
  lastUpdatedBy?: number;
  legalContingentCode?: any;
  lienAmount?: number;
  lienDateTimeCreated: string;
  lienReferenceNumber?: any;
  lmsApplicationDetailId?: number;
  loanApplicationCollateral?: any;
  loanApplicationDetail: Array<any>;
  loanApplicationDetailId?: number;
  loanApplicationId: number;
  loanApplicationIdForOperation?: any;
  loanApprovedLimitId?: any;
  loanId?: any;
  loanInformation: string;
  loanPreliminaryEvaluationId?: any;
  loanPurpose?: any;
  loanReferenceNumber?: any;
  loanStatus?: any;
  loanStatusId?: number;
  loanSystemTypeId?: number;
  loanTypeId: number;
  loanTypeName: string;
  loansWithOthers?: number;
  loantermSheetCode?: any;
  loantermSheetId?: any;
  maturityDate?: any;
  middleName?: any;
  misCode: string;
  monthlyPayment?: number;
  moratrium?: any;
  newApplicationDate?: any;
  notInBlackbook: boolean;
  notInCamsol: boolean;
  notInCrc: boolean;
  notInNegativeCrms: boolean;
  notInXds: boolean;
  operationId: number;
  operationName?: any;
  operationTypeName?: any;
  owner: boolean;
  ownershipStructure?: any;
  passCode?: any;
  pledgeCollateral?: any;
  principalAmount?: number;
  productClassId: number;
  productClassName: string;
  productClassProcessId: 1;
  productId?: number;
  productName?: any;
  productTypeId?: number;
  proposedAmount?: number;
  proposedInterestRate?: number;
  proposedProductId?: number;
  proposedProductName?: any;
  proposedTenor?: number;
  psrReportTypeId?: number;
  rac?: any;
  referenceNumber?: any;
  regionId: number;
  relatedEmployerId?: any;
  relatedReferenceNumber?: any;
  relationshipManagerId: number;
  relationshipManagerName: string;
  relationshipOfficerId: number;
  relationshipOfficerName: string;
  repaymentScheduleId?: any;
  repaymentTerm?: any;
  reportTypeName?: any;
  requireCollateral: true;
  requireCollateralTypeId: number;
  responseStaffId?: any;
  responsiblePerson?: any;
  reviewLoanDetaile?: any;
  sectorId?: number;
  sectorName?: any;
  singleCustomerId?: any;
  slaGlobalStatus: string;
  slaInduvidualStatus: string;
  slaTime: string;
  sourceBranchId?: number;
  sourceReferenceNumber?: any;
  staffId?: number;
  staffName?: any;
  subSectorId?: number;
  submittedForAppraisal: boolean;
  systemArrivalDateTime?: any;
  systemCurrentDate?: any;
  systemDateTime: string;
  teamMisCode?: any;
  
  tempApplicationCancellationId?: number;
  tenor?: number;
  tenorModeId?: number;
  tenorModeName?: any;
  tenorString: string;
  termSheetCode?: any;
  timeIn: string;
  timeLapse: string;
  toStaffId: number;
  totalUtilized?: number;
  tranchLevelId?: any;
  userBranchId?: number;
  userIPAddress?: any;
  username?: any;
  valueOfCollateral?: number;
  success: boolean;
}
